extends Node

enum PassiveAbility {
	HEAL_EVERY_TURN,
	CHANCE_FOR_EXTRA_MOVEMENT,
	CHANCE_FOR_RANDOM_BUFF,
	CHANCE_TO_WEAKEN_DEBUFFS,
	IMMUNE_TO_STUN,
	IMMUNE_TO_BURN,
	IMMUNE_TO_FREEZING,
	RESISTANT_TO_STATUS_EFFECTS,
	RESISTANT_TO_DEBUFFS,
	IMMUNE_TO_CRITICAL_HITS,
	DOUBLE_CRITICAL_HIT_RATE,
	NO_MOVEMENT_PENALTY_WHEN_CROSSING_OBSTACLES,
	N,
}
